alvr-org/PhoneVR

- code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
- code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj
- code/windows/PhoneVR/PhoneVR/driver.cpp
1. Updated VS TargetPlatform.
2. Re-written PVRStartConnectionListener() in ServerProvider::Init() to return from all paths. Removed MACRO VR_INIT_SERVER_DRIVER_CONTEXT.
> Updating and rewriting

- code/.gitignore
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/MainActivity.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
- code/mobile/android/PhoneVR/app/src/main/res/values/styles.xml
fixed some errors regarding sharedpreferences on MainActivity.kt and SettingsActivity.kt
and add 2 lines of code in styles.xml
> updated code

- code/common/src/PVRSocketUtils.cpp
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Wrap.kt
- code/mobile/mobile-common/PVRSockets.cpp
Relocating calls post onCreate, Network socket exception handling and exposing static functions to JNI
> Android fix

- code/common/libs/eigen/src/Core/arch/Default/BFloat16.h
- code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj
fixing compiler warnings on windows
> fixing compiler warnings

- code/common/src/PVRGlobals.cpp
- code/common/src/PVRGlobals.h
- code/windows/PhoneVR/PhoneVR/PVRFileManager.h
- code/windows/PhoneVR/PhoneVR/PVRGraphics.cpp
- code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
- code/windows/PhoneVR/PhoneVR/driver.cpp
* This brief Info log is also available for Release Builds.
* Debug Logs are only available for debug builds, and debug log causes much lag and frame drops because of invocation in Worker threads(only meant for development)
* Log files are seperated for both Log types.
> Windriver: Added a seperate Info Log

- README.md
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Globals.kt
- code/mobile/android/PhoneVR/app/src/main/res/layout/content_main.xml
- driver/bin/pvrsettings.json
Added more Description, Status, Notes to Home screen of Android App.
> Updated MainActivity, Troubleshooting tips, Defaulting pairing port

- README.md
- appveyor.yml
- code/windows/PhoneVR/PhoneVR/driver.cpp
Fixing FIle not Found Error on SteamVR and Added some Documentation on Issues.
> Fixing FIle not Found Error on SteamVR

- README.md
- code/common/src/PVRGlobals.cpp
- code/common/src/PVRGlobals.h
- code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/MainActivity.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/Wrap.kt
- code/mobile/android/PhoneVR/app/src/main/res/layout/activity_settings.xml
- code/mobile/mobile-common/PVRSockets.cpp
1. Added Logging for both Release and Debug Builds on android (LogCat, Logfiles, Brief Information Log in Settings Activity)
2. Request for External Storage Writing and reading Persmission
3. setOnSystemUiVisibilityChangeListener is now deprecated SDKv30, implemeting setOnApplyWindowInsetsListener for GameActivity.
Default Log paths : .../Android/data/virtualis.phonevr/files/PVR/[pvrlog.txt or pvrDebugLog.txt (only active in debug build)]
> Added Android Logging Debug|Release

- code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj
Adding explicit backward compatibility till Windows 7. Using Win8.1 SDK which is officially backward compatible with Win7 to avoid any future issues.
> [Win] Adding explicit backward compatibility

- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/GameActivity.kt
Show Average (5sample) FPS instead of instantaneous FPS.
> Show Average FPS instead of instantaneous

- code/common/src/PVRGlobals.cpp
Added Timestamps to Android logs (debug and release logs)
> Added Timestamps to Android logs

- code/common/src/PVRSocketUtils.cpp
- code/mobile/mobile-common/PVRSockets.cpp
- code/windows/PhoneVR/PhoneVR/driver.cpp
Added Extra info messages for network debugging on both Windows and Android end.
> [Win] Added Extra Network info log messages

- code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
Info Logging socket errors for networking issues
> [Win] Info Logging socket errors

- code/mobile/android/PhoneVR/app/build.gradle
- code/mobile/android/PhoneVR/app/src/main/AndroidManifest.xml
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/ErrorReporting.java
Implemented Application Crash Reports for Android (ARCA) 5.7 https://github.com/ACRA/acra in mailTo method
> [Android] Added Crash reporting

- README.md
- code/mobile/android/PhoneVR/app/build-pr.gradle
- code/mobile/android/PhoneVR/app/build.gradle
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/DiscordReportSender.java
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/DiscordReportSenderFactory.java
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/ErrorReporting.java
- code/mobile/android/PhoneVR/app/src/main/res/values/strings.xml
1. Liked Build Number to Appveyor Buld Number
2. Added Crashhandler and reporter with a small discord integration
> [Android] Added Crash Reporter with ACRA

- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
Invalid format exception fix `java.lang.RuntimeException: Unable to pause activity {viritualisres.phonevr/viritualisres.phonevr.SettingsActivity}: java.lang.NumberFormatException: For input string`
> [Android] Fix Crash @ Settings.kt NUmberFormatException

- code/common/src/PVRGlobals.cpp
- code/common/src/Utils/ThreadUtils.h
- code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
- code/mobile/mobile-common/PVRRenderer.cpp
- code/mobile/mobile-common/PVRSockets.cpp
- code/mobile/mobile-common/Utils/RenderUtils.cpp
For more descriptive logging, to resolve issues #49 and #43
> Adding Error Handling in PVRGlobals & native-lib

- code/mobile/mobile-common/Utils/RenderUtils.cpp
@ShootingKing-AM Requesting you to please review.
> [Android] Error Handling OpenGL functions [RenderUtils.cpp]

- code/common/libs/ifaddrs/ifaddrs.c
Fix iffaddrs stack corruption in some android devices, pointed out by issue #43.
Patch applied from https://github.com/morristech/android-ifaddrs/pull/5.
> [Andorid] Patch core network iffaddrs to fix Stack Corruption

- code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp
- code/mobile/mobile-common/PVRRenderer.cpp
- code/mobile/mobile-common/PVRSockets.cpp
- code/mobile/mobile-common/Utils/RenderUtils.cpp
1. Removing extra logging into release build logs
2. Removing unncessary java-runtime-exception checks
3. Log GLSL prog when compile failed
4. Adding proper casts in OpenGL logging.
5. Typos
> [Android] Optimizing release build

- code/mobile/android/PhoneVR/app/src/main/AndroidManifest.xml
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/SettingsActivity.kt
- code/mobile/android/PhoneVR/app/src/main/res/layout/activity_settings.xml
- code/mobile/android/PhoneVR/app/src/main/res/values/strings.xml
- code/mobile/android/PhoneVR/app/src/main/res/xml/provider_paths_app.xml
Add ShareLogs and OpenLogs buttons in Settings Activity
> [Android] Add ShareLogs and OpenLogs buttons

- appveyor.yml
> Remove deploy and release in appveyor.yml

- code/mobile/android/PhoneVR/app/build.gradle
- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/ALVRActivityTest.kt
- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/AppPackageTest.kt
- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/InitActivityTest.kt
- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/MainActivityTest.kt
- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/SettingsActivityTest.kt
- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/utils/pvr-adb-telnet.sh
- code/mobile/android/PhoneVR/build.gradle
- Basic Screenshot instrumentation tests
> tests: Implemented basic SS instrumentation tests for critical app paths

- code/mobile/android/PhoneVR/app/build.gradle
- This should fix failing release build in #117
> build: Update build.gradle APK release config

- .github/workflows/release.yml
- code/common/src/PVRGlobals.h
- code/common/src/version.info
- code/mobile/android/PhoneVR/app/build.gradle
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/InitActivity.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/MainActivity.kt
- code/mobile/android/PhoneVR/version.properties
- code/mobile/android/PhoneVR/versioning.gradle
- code/windows/PhoneVR/PhoneVR/PVRSockets.cpp
- code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj
- code/windows/PhoneVR/PhoneVR/PhoneVR.vcxproj.filters
- code/windows/PhoneVR/PhoneVR/driver.cpp
- code/windows/PhoneVR/PhoneVR/resource.h
- code/windows/PhoneVR/PhoneVR/resource.rc
> Implement versioning

- code/mobile/android/PhoneVR/app/build.gradle
- code/mobile/android/PhoneVR/app/src/main/AndroidManifest.xml
- code/mobile/android/PhoneVR/app/src/main/cpp/alvr_main.cpp
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/ALVRActivity.java
fixes https://github.com/alvr-org/ALVR/issues/1583
fixes https://github.com/PhoneVR-Developers/PhoneVR/issues/129
ps: for this PR to be fully functional and working need https://github.com/alvr-org/ALVR/pull/1801 update in ALVR server
> fix: squashing some 🐛 

- .github/workflows/build.yml
- to fix test flakyness for starting up and running AVD
- cleanup and save cache on failure too
> ci: Implement more redudency for AVD tests

- code/mobile/android/PhoneVR/app/src/androidTest/java/viritualisres/phonevr/ALVRActivityTest.kt
- code/mobile/android/PhoneVR/app/src/main/java/viritualisres/phonevr/ALVRActivity.java
- code/mobile/android/PhoneVR/app/src/main/res/menu/settings_menu.xml
- code/mobile/android/PhoneVR/app/src/main/res/values/strings.xml
> Implemented max brightness toggle feature and other tests

- .github/workflows/build.yml
- macos-14 image is not working properly rn, should fix later
> fix: macos CI by using macos-12
